name: Run Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install pytest pytest-pylint pytest-cov
        pip install faker
        pip install python-dotenv

    - name: Run Tests
      run: |
        pytest --cov=calculator --cov-report=xml
